### PR TITLE
Add ietf-http-doh for bare http DoH

### PR DESCRIPTION
**Pull request by jimpick**

### CODE REVIEW

**Comment by jimpick** [comment]
Oops, I didn't mean to send this PR upstream.

**Comment by leiless** [comment]
I wonder what is the use case for plain HTTP (insecure) DoH?

**Comment by jimpick** [comment]
I'm using it internally in a Kubernetes cluster. I'm hosting a bunch of DoH servers as Knative services (that spin to zero when not in use). I have a proxy CoreDNS server that listens on UDP port 53 that translates calls. I found dnsredir was able to make DoH requests. As these are "internal" queries, using plain HTTP is more convenient because then I don't need to setup SSL certs. It's definitely an exotic setup. :-)

**Comment by leiless** [comment]
OK, that's great. I think it's a good way since it's an internal DoH service.

As for performance consideration, UDP might be a better choice since there is no TCP three-way handshake.
The latency should be lower than TCP.

**Comment by jimpick** [comment]
Kubernetes is OK with UDP services, but Knative can only do HTTP/HTTPS. I'm not too concerned with performance... it's more of an experiment to see if I can do (possibly) millions of infrequently accessed zone files on low-end cloud hardware.

**Comment by leiless** [comment]
Great! Have fun!

**Pull request closed without merging**
